"""Add address boom

Revision ID: 062728dbad66
Revises: f630695dbcaf
Create Date: 2022-03-31 20:23:41.899017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062728dbad66'
down_revision = 'f630695dbcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
